sudo: false
language: node_js
node_js:
  - "0"
  - "4"
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ./node_modules/lerna/bin/lerna.js bootstrap
  - ./node_modules/lerna/bin/lerna.js run test

